name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    # 【変更箇所1】pytest-html をインストールさせる
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-playwright pytest-html

    - name: Install Playwright Browsers
      run: python -m playwright install chromium

    # 【変更箇所2】レポートを出力するコマンドに変更する
    - name: Run Playwright tests and generate report
      run: python -m pytest --html=report.html --self-contained-html

    # 【新規追加】クラウド上で生成された report.html を「成果物」として保存する
    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      if: always() # テストが途中で失敗(エラー)しても、必ずレポートは保存させるための絶対条件
      with:
        name: playwright-report # 保存されるZIPファイルの名前
        path: report.html
        retention-days: 14 # サーバーの容量節約のため、14日で自動削除する設定